INSERT INTO `questiondata`(`ID`, `Qst`, `Opt1`, `Opt2`, `Opt3`) VALUES (0001, 'What is Cristiano Ronaldo\'s main profession?', 'A football player', 'An actor', 'A model');
INSERT INTO `questiondata`(`ID`, `Qst`, `Opt1`, `Opt2`, `Opt3`) VALUES (0002, 'What is the capital city of Syria?', 'Damascus', 'Cairo', 'Baghdad');
INSERT INTO `questiondata`(`ID`, `Qst`, `Opt1`, `Opt2`, `Opt3`) VALUES (0003, 'Which automobile brand has four circles in their logo?', 'Audi', 'BMW', 'Mercedes-Benz');
INSERT INTO `questiondata`(`ID`, `Qst`, `Opt1`, `Opt2`, `Opt3`) VALUES (0004, 'Who is Michael Jordan?', 'A basketball player', 'A president', 'An E-Sport player');
INSERT INTO `questiondata`(`ID`, `Qst`, `Opt1`, `Opt2`, `Opt3`) VALUES (0005, 'What is the population of China?', 'Around 1,38 billion', 'Around 1,62 billion', 'Around 0,98 billion');
INSERT INTO `questiondata`(`ID`, `Qst`, `Opt1`, `Opt2`, `Opt3`) VALUES (0006, 'Who was the first human in outer space?', 'Yuri Gagarin', 'Neil Armstrong', 'Niels Amsterdam');
INSERT INTO `questiondata`(`ID`, `Qst`, `Opt1`, `Opt2`, `Opt3`) VALUES (0007, 'Which meal is the most caloric? (100g serving)', 'Macadamia Nuts', 'Salmon', 'Avocado');
INSERT INTO `questiondata`(`ID`, `Qst`, `Opt1`, `Opt2`, `Opt3`) VALUES (0008, 'Which country is the biggest in the world?', 'Russia', 'China', 'USA');
INSERT INTO `questiondata`(`ID`, `Qst`, `Opt1`, `Opt2`, `Opt3`) VALUES (0009, 'What is Russian Standard?', 'Vodka', 'Special tea made out of potatoes', 'Beer brand');
INSERT INTO `questiondata`(`ID`, `Qst`, `Opt1`, `Opt2`, `Opt3`) VALUES (0010, 'What is the capital city of Australia?', 'Canberra', 'Sydney', 'Perth');
INSERT INTO `questiondata`(`ID`, `Qst`, `Opt1`, `Opt2`, `Opt3`) VALUES (0011, 'What was the most known Russian tank during the WW2?', 'T-34', 'Tiger I', 'M4 Sherman');
INSERT INTO `questiondata`(`ID`, `Qst`, `Opt1`, `Opt2`, `Opt3`) VALUES (0012, 'Where did the brand by the name of Ford originate?', 'USA', 'Poland', 'Italy');
INSERT INTO `questiondata`(`ID`, `Qst`, `Opt1`, `Opt2`, `Opt3`) VALUES (0013, 'Where was Keanu Reeves born?', 'Lebanon', 'Canada', 'Brazil');
INSERT INTO `questiondata`(`ID`, `Qst`, `Opt1`, `Opt2`, `Opt3`) VALUES (0014, 'Which character did Andy Serkis portray in The Lord of the Rings?', 'Gollum', 'Faramir', 'Sauron');
INSERT INTO `questiondata`(`ID`, `Qst`, `Opt1`, `Opt2`, `Opt3`) VALUES (0015, 'Who played Arthur in the 2019 Joker movie?', 'Joaquin Phoenix', 'Martin Lawrence', 'Daniel Craig');
INSERT INTO `questiondata`(`ID`, `Qst`, `Opt1`, `Opt2`, `Opt3`) VALUES (0016, 'Which horror movie did Bill Skarsgård play in?', 'IT', 'The Orphanage', 'A Nightmare on Elm Street');
INSERT INTO `questiondata`(`ID`, `Qst`, `Opt1`, `Opt2`, `Opt3`) VALUES (0017, 'Which time of the year does the famous Oktoberfest take place?', 'September', 'October', 'November');
INSERT INTO `questiondata`(`ID`, `Qst`, `Opt1`, `Opt2`, `Opt3`) VALUES (0018, 'When did Michael Jackson die?', '2009', '2011', '2007');
INSERT INTO `questiondata`(`ID`, `Qst`, `Opt1`, `Opt2`, `Opt3`) VALUES (0019, 'Who is the founder of Apple company?', 'Steve Jobs', 'Bill Gates', 'Elon Musk');
INSERT INTO `questiondata`(`ID`, `Qst`, `Opt1`, `Opt2`, `Opt3`) VALUES (0020, 'What is Nokia 3310 most famous for?', 'Its indestructibleness', 'Its 24-karat gold decoration', 'Not using Android OS');
